# Cloudflare Wrangler configuration for Outline MCP Server
name = "outline-mcp-server"
main = "build/worker/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Durable Objects bindings for default environment
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "OutlineMCP"

# Worker configuration
[env.production]
name = "outline-mcp-server"
[env.production.vars]
OUTLINE_MCP_HOST = "0.0.0.0"
OUTLINE_MCP_PORT = "8080"

[[env.production.durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "OutlineMCP"

[env.staging]
name = "outline-mcp-server-staging"
[env.staging.vars]
OUTLINE_MCP_HOST = "0.0.0.0"
OUTLINE_MCP_PORT = "8080"

[[env.staging.durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "OutlineMCP"

# Environment variables that need to be set in Cloudflare dashboard
# or via wrangler secret put commands

# Secrets (set these using: wrangler secret put OUTLINE_API_KEY)
# Required secrets:
# - OUTLINE_API_KEY: Your Outline API key
# - OUTLINE_API_URL: Your Outline API URL (e.g., https://app.getoutline.com/api)

# Build configuration
[build]
command = "npm run build:worker"

# Assets configuration for static files
[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["OutlineMCP"]

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "MCP_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Routes configuration
# Uncomment and modify these if you want to use custom domains
# [env.production]
# routes = [
#   { pattern = "mcp.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# [env.staging]
# routes = [
#   { pattern = "mcp-staging.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Limits and resource allocation
# Note: CPU limits require a paid Cloudflare Workers plan
# [limits]
# cpu_ms = 30000

# Analytics and observability
[observability]
enabled = true

# Triggers (for scheduled tasks if needed)
# [[triggers.crons]]
# cron = "0 0 * * *"
# globs = ["src/scheduled/*.js"]
